[workspace]
members = [
  "contracts/*",
  "packages/*",
  "scripts",
]

[workspace.package]
version = "0.1.0"
authors = []
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Keep as is until TendermintStake updates.
[workspace.dependencies]
abstract-sdk = "0.4.3"
abstract-api = "0.4.3"
abstract-app = "0.4.3"
abstract-os = "0.4.3"
cosmwasm-std = { version = "1.1" }
cosmwasm-schema = { version = "1.1" }
cw-asset = { version = "2.2" }
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cw-storage-plus = "0.16.0"
cw-controllers = "0.16.0"
cw-paginate = {git = "https://github.com/DA0-DA0/dao-contracts.git"}
cosmwasm-storage = { version = "1.1" }
cw-utils = "0.16"
cw2 = "0.16"
cw20 = "0.16"
cw20-base = "0.16"
anyhow = { version = "1.0.51" }
cw-multi-test = "0.16"
