[package]
name = "autocompounder"
description = "Autocompounder allows for autocompounding of LP positions. Built on Abstract."
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false


exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { workspace = true }
cw-asset = { workspace = true }
cw-controllers = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw20-base = { workspace = true, features = ["library"] }
schemars = "0.8.1"
serde = { workspace = true }
thiserror = { version = "1.0.21" }
lazy_static = "1.4.0"
forty-two = { workspace = true }

abstract-app = { workspace = true }
abstract-sdk = { workspace = true }
protobuf = { version = "2", features = ["with-bytes"] }
cw-utils = {workspace = true}

[dev-dependencies]
forty-two-boot = {path = "../../packages/forty-two-boot" }
forty-two = { workspace = true, features = ["boot"] }
cw-staking = { path = "../../contracts/cw-staking" }

abstract-app = { workspace = true, features = ["schema"] }
abstract-os = { workspace = true }
cw-multi-test = { workspace = true , features = ["staking"]}
module-factory = {git = "https://github.com/Abstract-OS/contracts.git",features = ["library"] }
os-factory = {git = "https://github.com/Abstract-OS/contracts.git",features = ["library"] }
ans-host = {git = "https://github.com/Abstract-OS/contracts.git",features = ["library"] }
version-control = {git = "https://github.com/Abstract-OS/contracts.git",features = ["library"] }
proxy = {git = "https://github.com/Abstract-OS/contracts.git",features = ["library"] }
manager = {git = "https://github.com/Abstract-OS/contracts.git",features = ["library"]}
# requires testing flag to ensure Astroport Msg type compatibility
dex = {git = "https://github.com/Abstract-OS/contracts.git", features = ["testing"]}
subscription = {git = "https://github.com/Abstract-OS/contracts.git",features = ["library"]}
abstract-boot = {workspace = true}
boot-core = { workspace = true}
boot-cw-plus = { workspace = true}
anyhow = {workspace = true}
rstest = {workspace = true }
speculoos = { workspace = true }
astroport = { workspace = true }
semver = { package = "cw-semver", version = "1" }

cw-astro = {package = "cw20", version = "0.15"}
astroport-token = { git = "https://github.com/astroport-fi/astroport-core.git"}
astroport-generator = { git = "https://github.com/astroport-fi/astroport-core.git"}
astroport-vesting = { git = "https://github.com/astroport-fi/astroport-core.git"}
astroport-staking = { git = "https://github.com/astroport-fi/astroport-core.git"}
astroport-factory = { git = "https://github.com/astroport-fi/astroport-core.git"}
astroport-pair = { git = "https://github.com/astroport-fi/astroport-core.git"}
astroport-pair-stable = { git = "https://github.com/astroport-fi/astroport-core.git"}
astroport-whitelist = { git = "https://github.com/astroport-fi/astroport-core.git"}
astroport-governance = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "main"}
generator-controller = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "main" }

voting-escrow = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "main" }
voting-escrow-delegation = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "main" }
astroport-nft = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "main" }
cw721-base = { version = "0.15", features = ["library"] }

generator-proxy-to-vkr = { git = "https://github.com/astroport-fi/astro-generator-proxy-contracts.git", branch = "main" }
valkyrie = { git = "https://github.com/valkyrieprotocol/contracts.git", rev = "b5fcb666f17d7e291f40365756e50fc0d7b9bf54"  }
valkyrie-lp-staking = { git = "https://github.com/valkyrieprotocol/contracts.git", rev = "b5fcb666f17d7e291f40365756e50fc0d7b9bf54" }
valkyrie-vp = { git = "https://github.com/valkyrieprotocol/contracts.git", rev = "b5fcb666f17d7e291f40365756e50fc0d7b9bf54" }

tokio = { workspace = true }
dotenv = {  workspace = true }
env_logger = {  workspace = true }

clap =  { workspace = true }
