[package]
name = "autocompounder"
version = {workspace = true}
authors = {workspace = true}
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-std = { workspace = true }
cw-asset = { workspace = true }
cw-controllers = { workspace = true }
cosmwasm-schema = { version = "1.1" }
cw-storage-plus = { workspace = true }
cw2 = "1.0.1"
cw20 = { version = "1.0.1" }
cw20-base = { version = "1.0.1", features = ["library"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }
semver = "1.0.0"
lazy_static = "1.4.0"
forty-two = { path = "../../packages/forty-two" }

abstract-app = { workspace = true, features = ["library"] }
abstract-sdk = { workspace = true }
protobuf = { version = "2", features = ["with-bytes"] }
cw-utils = {workspace = true}

[dev-dependencies]
abstract-app = { workspace = true, features = ["schema"] }
abstract-os = { workspace = true }
cw-multi-test = { workspace = true , features = ["staking"]}
cw20 = { workspace = true }
abstract-boot = {workspace = true}
boot-core = { workspace = true}
anyhow = {workspace = true}
os-factory = { workspace = true }
module-factory = { workspace = true }
ans-host = { workspace = true }
version-control = { workspace = true }
proxy = { workspace = true }
manager = { workspace = true }
rstest = {workspace = true }
speculoos = { workspace = true }
astroport = { workspace = true }


