[package]
name = "forty-two-boot"
version = "1.1.1"
edition = "2021"
#workspace.version = true
#workspace.authors = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-asset = { workspace = true }
cosmwasm-std = { workspace = true }
boot-core = "0.2.0"
boot-cw-plus = "0.2.0"
abstract-boot = "0.2.0-beta.7"
serde_json = "1.0.79"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cw-staking = { package = "cw-staking", path = "../../contracts/cw-staking" }
forty-two = { path = "../forty-two" }
abstract-os = { workspace = true}
