name: coverage
on: [push]
jobs:
  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ABSTRACT_SSH_PRIVATE_KEY }}
      - name: Disable incremental compilation
      # Disable incremental compilation to save diskspace (the CI doesn't recompile modified files)
      # https://github.com/apache/arrow-datafusion/issues/6676
        shell: bash
        run: |
          echo 'rustflags = ["-C", "incremental=no"]' >> $GITHUB_WORKSPACE/contracts/Cargo.toml
      - name: Fix git ownership
        run: |
          git config --global --add safe.directory /__w/contracts/contracts
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --workspace --out Xml
      - name: Upload coverage reports to Codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        uses: codecov/codecov-action@v3
